[package]
name = "sen5x-rs"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "A no_std Rust driver for Sensirion SEN5x air quality sensors"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sylvain-bouchard/sen55-rs"
keywords = ["embedded", "sensor", "sensirion", "sen55", "sen5x"]
categories = ["embedded", "no-std", "hardware-support"]

[dependencies]
embedded-hal-async = "1.0"
sen5x-conversion = { path = "../sen5x-conversion" }

[dev-dependencies]
pollster = "0.4"
